### PR TITLE
add buttons to open notebooks in Amazon SageMaker Studio Lab

### PR DESCRIPTION
**Pull request by kmotohas**
Added support for [Amazon SageMaker Studio Lab](https://studiolab.sagemaker.aws/), a free JupyterLab environment.

Summary:
- Add "Open Studio Lab" buttons to README.md
- Add environment.yaml to create a conda environment
- (Fix broken links to nbviewer)

I have verified that all the links I have added are working correctly and that I can open the notebooks on SageMaker Studio Lab without any problems.

### CODE REVIEW

**Comment by ctgk** [comment]
@kmotohas 
Thanks for your pull request!
Direct links to computing environment would be a nice way to show the notebooks.

Is there any way to make animation in the 4th cell running?
I could not see the animation running in the page, which may be my fault as I still don't have an account and requesting one.
https://studiolab.sagemaker.aws/import/github/ctgk/PRML/blob/main/notebooks/ch10_Approximate_Inference.ipynb

**Comment by kmotohas** [comment]
Great catch... The 4th cell in the ch10 notebook fails because ffmpeg is not available for now. Let me try to find a workaround.

**Comment by kmotohas** [comment]
It works after `conda install ffmpeg` :)

Screen-Recording-2022-05-10-at-22 30 02

**Comment by ctgk** [comment]
I still could not see the animation running in [the page](https://studiolab.sagemaker.aws/import/github/kmotohas/PRML/blob/main/notebooks/ch10_Approximate_Inference.ipynb).
(note that the link is to 'kmotohas' not 'ctgk')
Would it be because I don't have an accout? Are there any ways for people without aws accout see the animation running?

**Comment by kmotohas** [comment]
A notebook in the page is rendered just for preview. I do not see the animation in my environment too.

If you have an (free) account of SageMaker Studio Lab, you can copy a notebook (or even the whole repository) to your SageMaker Studio Lab workspace (AWS-managed JupyterLab).

image

A notebook or repository is copied by clicking a 'Copy to project' button. After that, you can interactively run and develop codes, and see the animation.

image

**Comment by ctgk** [comment]
@kmotohas 
Got it. Since there are nbviewer links as well in your request, it shouldn't be a big problem.
I will merge yours to my branch. Thanks for your contribution.

**Pull request merged**
